# Generated by Django 2.0 on 2018-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
